import Head from 'next/head';
import React, { useState, useEffect } from "react";
import CardDetail from "../components/cardDetail";
import Filter from "../components/filter";
import { CardDetailSkeleton } from "../components/skeleton";
import axios from "axios";

const Dev = () => {
    const [data, setData] = useState([]);

    useEffect(() => {
      axios.get('/api/filterCourses')
        .then(res => setData(res.data))
        .catch(err => console.log(err));
    }, []);

  return (
    <div>
      <Head>
        <title>Coursurf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="search-head">
        Search result for <b>Python</b>
        <div className="search-count">{"1515"} courses</div>
      </div>
      <div className="search-dir">
        <div className="filter">
          <Filter />
        </div>
        <main>
          <div className="card-header">
            <div className="showing">
              Showing <b>{1515} courses</b>
            </div>

            <select name="category" id="cars" placeholder="Sort by Relevency">
              {/* <option value selected>Sort by Relevency</option> */}
              <option value="relevency">Relevency</option>
              <option value="rated-up">Highest Rated</option>
              <option value="rated-down">Lowest Rated</option>
              <option value="created-up">Most Recently Added</option>
            </select>
          </div>
          <div className="cards">
            {/* <CardDetail />
            <CardDetail />
            <CardDetail />
            <CardDetail />
            <CardDetail />
            <CardDetail />
            <CardDetail />
            <CardDetail />
            <CardDetailSkeleton />
            <CardDetail /> */}
            {data.map((ite) => (
              <CardDetail
                key={ite.link}
                title={ite.name}
                content={ite.description}
                provider={ite.provider}
                duration={ite.duration}
                pricing={ite.pricing}
              />
            ))}
          </div>
        </main>
      </div>

      {/* <ReactStars
                count={5}
                onChange={ratingChanged}
                size={24}
                color2={'#ffd700'} /> */}
    </div>
  );
};

export default Dev;


  

