import Head from 'next/head';
import Card from '../components/Card';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coursurf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl">Coursurf</h1>
      <h1 className="text-3xl">Coursurf</h1>
      <h1 className="text-3xl">Coursurf</h1>
      <div className="flex flex-col justify-center items-center w-full h-full">

        <div className='card-container'>
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
        <h1 className="text-3xl">Coursurf</h1>
      </div>
    </div>
  );
}
