import Head from 'next/head';
import Card, { CardSkeleton } from '../components/cardMain';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coursurf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="card-container">
      <CardSkeleton />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
      </div>
    </div>
  );
}
